import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';

import {publishComponentDesignHtml as publishComponentDesignHtmlRaw} from './component-design-html.mjs';
import {createUxTestSpec} from './ux-test-fixture.mjs';

const fixtureFile = new URL('../references/component-design-proposal.json', import.meta.url);
const designFixtureFile = new URL('../references/extras-proposal.json', import.meta.url);
const fixture = () => JSON.parse(fs.readFileSync(fixtureFile, 'utf8'));
const folder = () => fs.mkdtempSync(path.join(os.tmpdir(), 'component-design-html-'));

function publishComponentDesignHtml(componentFile, uxFile, designFile, output, options = {}) {
  return publishComponentDesignHtmlRaw(componentFile, uxFile, designFile, output, {
    sourceRoot: path.dirname(path.resolve(componentFile)),
    ...options,
  });
}

function ux() {
  return createUxTestSpec();
}

function design() {
  const {baseRevision: _baseRevision, ...proposal} = JSON.parse(fs.readFileSync(designFixtureFile, 'utf8'));
  proposal.theme.id = 'example-theme';
  return {...proposal, id: 'example-design', revision: 1, status: 'accepted', decisions: []};
}

function sources(base, component = fixture()) {
  const componentFile = path.join(base, 'component.json');
  const uxFile = path.join(base, 'ux.json');
  const designFile = path.join(base, 'design.json');
  fs.writeFileSync(componentFile, `${JSON.stringify(component, null, 2)}\n`);
  fs.writeFileSync(uxFile, `${JSON.stringify(ux(), null, 2)}\n`);
  fs.writeFileSync(designFile, `${JSON.stringify(design(), null, 2)}\n`);
  return {componentFile, uxFile, designFile};
}

function snapshot(output) {
  return ['component-comps/index.html', 'component-comps/record-list-available.html', 'component-comps/record-list-available-annotated.html', 'assets/component-composition.css', 'assets/prd.css', 'assets/fonts/roboto.ttf', 'assets/fonts/roboto-OFL.txt', 'ui/components/record-list-component-render-report.json']
    .map(relative => [relative, fs.readFileSync(path.join(output, relative))]);
}

function sceneMarkup(html) {
  const start = html.indexOf('<div class="ui-viewport"');
  const end = html.lastIndexOf('</div>\n    </section>');
  return html.slice(start, end);
}

test('publishes deterministic focused component comps from one state scene', () => {
  const base = folder();
  const input = sources(base);
  const output = path.join(base, 'prd');
  const first = publishComponentDesignHtml(input.componentFile, input.uxFile, input.designFile, output);
  const before = snapshot(output);
  const clean = before[1][1].toString();
  const annotated = before[2][1].toString();
  assert.equal(first.rendererVersion, 'component-design-html-1.2');
  assert.equal(first.componentTemplate.id, 'record-list-component');
  assert.equal(first.artifactKind, 'comp');
  assert.match(before[0][1].toString(), /Component comps/);
  assert.match(clean, /ui-visual--item/);
  assert.match(clean, /\.\.\/assets\/component-composition\.css/);
  assert.equal(sceneMarkup(clean), sceneMarkup(annotated));
  assert.match(before[3][1].toString(), /\.ui-visual--selection/);
  assert.match(before[3][1].toString(), /body:has\(#scene:target\)/);
  assert.match(before[3][1].toString(), /#scene \{ width: 100%; zoom: 1 !important; \}/);
  assert.match(before[4][1].toString(), /Generated by refine-design:design-language-html:v1/);
  assert.ok(before[5][1].length > 1000);

  publishComponentDesignHtml(input.componentFile, input.uxFile, input.designFile, output);
  assert.deepEqual(snapshot(output), before);
});

test('labels a wireframe honestly in focused output', () => {
  const base = folder();
  const wireframe = fixture();
  wireframe.artifactKind = 'wireframe';
  wireframe.fidelity = {missingForComp: ['Representative content and finished styling are not designed.']};
  const input = sources(base, wireframe);
  const output = path.join(base, 'prd');
  const result = publishComponentDesignHtml(input.componentFile, input.uxFile, input.designFile, output);
  assert.equal(result.artifactKind, 'wireframe');
  assert.match(fs.readFileSync(path.join(output, 'component-comps', 'index.html'), 'utf8'), /Component Wireframes/);
});

test('invalid component input preserves a prior publication', () => {
  const base = folder();
  const input = sources(base);
  const output = path.join(base, 'prd');
  publishComponentDesignHtml(input.componentFile, input.uxFile, input.designFile, output);
  const before = snapshot(output);
  const invalid = fixture();
  invalid.componentTemplate.stateScenes = [];
  fs.writeFileSync(input.componentFile, JSON.stringify(invalid));
  assert.throws(() => publishComponentDesignHtml(input.componentFile, input.uxFile, input.designFile, output), /must match the component state set/);
  assert.deepEqual(snapshot(output), before);
});

test('refuses unowned component output and linked roots', () => {
  const base = folder();
  const input = sources(base);
  const unowned = path.join(base, 'unowned');
  fs.mkdirSync(path.join(unowned, 'component-comps'), {recursive: true});
  fs.writeFileSync(path.join(unowned, 'component-comps', 'index.html'), '<h1>Owner file</h1>');
  assert.throws(() => publishComponentDesignHtml(input.componentFile, input.uxFile, input.designFile, unowned), /unowned generated file/);

  const actual = path.join(base, 'actual');
  const linked = path.join(base, 'linked');
  fs.mkdirSync(actual);
  fs.symlinkSync(actual, linked, process.platform === 'win32' ? 'junction' : 'dir');
  assert.throws(() => publishComponentDesignHtml(input.componentFile, input.uxFile, input.designFile, linked), /linked output root/);
});
