import {createHash} from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

import {validate as validateDesignLanguage} from './design-language.mjs';
import {publishDesignLanguageHtml} from './design-language-html.mjs';
import {iconGeometry} from './design-language-icons.mjs';
import {authorizeAssetRoot} from './input-security.mjs';
import {validateUxSpec} from './ux-design.mjs';
import {buildUiCompositionHtml, renderInlineScene, UI_COMPOSITION_HTML_GENERATOR, UI_COMPOSITION_HTML_MARKER} from './ui-composition-html.mjs';
import {buildComponentRegistration} from './component-design.mjs';
import {buildComponentDesignHtml, COMPONENT_DESIGN_HTML_GENERATOR} from './component-design-html.mjs';
import {renderSurfaceInteractionWireframes, renderUxInteractionWireframeCss} from './ux-interaction-wireframe.mjs';

const GENERATOR = 'refine-design:prd-html:v1';
const VERSION = 'prd-html-1.8';
const TEXT_MARKER = `Generated by ${GENERATOR}`;
const DESIGN_GENERATOR = 'refine-design:design-language-html:v1';

function fail(message) {
    throw new Error(message);
}

function escapeHtml(value) {
    return String(value).replace(/[&<>"']/g, (character) => ({
        '&': '&amp;',
        '<': '&lt;',
        '>': '&gt;',
        '"': '&quot;',
        "'": '&#39;',
    })[character]);
}

function sourceHash(source) {
    return createHash('sha256').update(source).digest('hex');
}

function readJson(file, label) {
    const absolute = path.resolve(file);
    let source;
    try { source = fs.readFileSync(absolute, 'utf8'); } catch { fail(`${label} is missing: ${absolute}`); }
    let value;
    try { value = JSON.parse(source); } catch { fail(`${label} is not valid JSON`); }
    return {absolute, source, value};
}

function anchor(kind, id) {
    return `${kind}-${encodeURIComponent(id)}`;
}

function idMap(records) {
    return new Map(records.map((record) => [record.id, record]));
}

function renderSiteNavigation(current, prefix = '', hasComps = false, hasComponentComps = false) {
    const items = [
        ['requirements', `${prefix}index.html`, 'Product requirements'],
        ['design-language', `${prefix}design-language/index.html`, 'Design language'],
        ['components', `${prefix}components/index.html`, 'Component states'],
        ...(hasComps ? [['comps', `${prefix}comps/index.html`, 'Product comps']] : []),
        ...(hasComponentComps ? [['component-comps', `${prefix}component-comps/index.html`, 'Component comps']] : []),
    ];
    return `<nav class="rd-site-nav" aria-label="Product requirements pages">${items.map(([id, href, label]) => id === current
        ? `<span aria-current="page">${label}</span>`
        : `<a href="${href}">${label}</a>`).join('')}</nav>`;
}

function attention(status) {
    if (status === 'locked') return '<p class="prd-attention"><strong>Locked design.</strong> Preserve this design unless the user explicitly requests a change to this scope.</p>';
    if (status === 'unresolved') return '<p class="prd-attention"><strong>Needs definition.</strong> This part of the design is still unresolved.</p>';
    if (status === 'proposed') return '<p class="prd-attention"><strong>Under consideration.</strong> This is an unselected alternative.</p>';
    return '';
}

function renderList(items, emptyText = 'None recorded.') {
    return items.length ? `<ul>${items.map((item) => `<li>${escapeHtml(item)}</li>`).join('')}</ul>` : `<p>${escapeHtml(emptyText)}</p>`;
}

function renderPrdIndex(spec, uiSpec = null, hasComponentComps = false, componentRegistrations = []) {
    const areas = idMap(spec.application.areas);
    const surfaces = idMap(spec.surfaces);
    const components = idMap(spec.components);
    const useCases = idMap(spec.useCases);
    const openQuestions = spec.openQuestions.filter((question) => question.status === 'open');
    const scenesBySurface = new Map(spec.surfaces.map(surface => [surface.id, uiSpec?.scenes.filter(scene => scene.surfaceRef === surface.id) ?? []]));
    const renderRequests = new Map((uiSpec?.renderRequests ?? []).map(request => [request.id, request]));
    const requestsForScene = sceneId => [...renderRequests.values()].filter(request => request.sceneRef === sceneId);
    const uiTemplates = new Map((uiSpec?.templates ?? []).map(template => [template.id, template]));
    const unresolvedPlaceholderCount = scene => {
        let count = 0;
        const visit = node => {
            if (node.kind === 'region') return node.children.forEach(visit);
            if (!node.placeholder) return;
            const template = uiTemplates.get(node.templateRef.id);
            const resolved = componentRegistrations.some(registration =>
                registration.replacesTemplateRef.id === template.id &&
                registration.replacesTemplateRef.version === template.version &&
                registration.stateOutputs[node.state]
            );
            if (!resolved) count += 1;
        };
        visit(scene.root);
        return count;
    };
    const artifactKind = scene => unresolvedPlaceholderCount(scene) > 0 ? 'wireframe' : 'comp';
    const compLinks = scene => requestsForScene(scene.id).map(request => {
        const kind = artifactKind(scene);
        return `<a href="${escapeHtml(request.output)}">${escapeHtml(request.variant === 'clean' ? `Clean ${kind}` : `Annotated ${kind}`)}</a>`;
    }).join('');
    const inlineComp = scene => {
        const clean = requestsForScene(scene.id).find(request => request.variant === 'clean');
        if (!clean) return '';
        const content = renderInlineScene(scene, uiSpec, {uxSpec: spec, componentRegistrations});
        const unresolvedCount = unresolvedPlaceholderCount(scene);
        const kind = artifactKind(scene);
        const partialNotice = unresolvedCount > 0
            ? `<p class="prd-attention"><strong>Partial UI wireframe.</strong> ${unresolvedCount} unresolved component ${unresolvedCount === 1 ? 'prevents' : 'prevent'} this scene from qualifying as a finished comp.</p>`
            : '';
        return `<figure class="prd-comp-inline"><div class="prd-comp-inline-heading"><div><p class="prd-kicker">${escapeHtml(scene.state)} · ${kind}</p><h4>${escapeHtml(scene.name)}</h4></div><div class="prd-comp-actions">${compLinks(scene)}</div></div>${partialNotice}${content}<figcaption>${escapeHtml(scene.viewport.width)} × ${escapeHtml(scene.viewport.height)} · ${kind}. Specialized components remain visibly labeled where their detailed comps have not yet been designed.</figcaption></figure>`;
    };
    const shellNavigation = spec.application.shell.navigation
        ? `<div><dt>Navigation</dt><dd><strong>${escapeHtml(spec.application.shell.navigation.pattern)}</strong><br>${escapeHtml(spec.application.shell.navigation.description)}</dd></div>`
        : '<div><dt>Navigation</dt><dd>Not specified yet.</dd></div>';
    const shellRegions = [...(spec.application.shell.regions ?? [])].sort((left, right) => left.order - right.order);
    const shellStack = shellRegions.length
        ? `<ol class="prd-shell-stack">${shellRegions.map(region => `<li><div><p class="prd-kicker">${escapeHtml(region.kind)} · ${escapeHtml(region.persistence)}</p><h4>${escapeHtml(region.name)}</h4><p>${escapeHtml(region.purpose)}</p></div></li>`).join('')}</ol>`
        : '<p class="prd-muted">Shell regions have not been specified yet.</p>';
    const supportingLinks = spec.supportingDocuments?.length
        ? `<div class="prd-supporting-links"><strong>Design references</strong>${spec.supportingDocuments.map(document => `<a href="${escapeHtml(document.path)}">${escapeHtml(document.label)}</a>`).join('')}</div>`
        : '';
    return `<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="generator" content="${GENERATOR}">
    <title>${escapeHtml(spec.product.name)} Product Requirements</title>
    <link rel="stylesheet" href="assets/prd.css">
    <link rel="stylesheet" href="assets/product.css">
    ${uiSpec ? '<link rel="stylesheet" href="assets/composition.css">' : ''}
</head>
<body>
    <!-- ${TEXT_MARKER} -->
    <a class="rd-skip-link" href="#main-content">Skip to content</a>
    <header class="rd-page-header">
        <div><p class="rd-eyebrow">Product requirements</p><h1>${escapeHtml(spec.product.name)}</h1><p class="rd-lede">${escapeHtml(spec.product.overview)}</p></div>
        <dl class="rd-source-summary"><div><dt>Revision</dt><dd>${escapeHtml(spec.revision)}</dd></div><div><dt>Design state</dt><dd>${escapeHtml(spec.status)}</dd></div><div><dt>Features</dt><dd>${spec.features.length}</dd></div><div><dt>Surfaces</dt><dd>${spec.surfaces.length}</dd></div></dl>
    </header>
    ${attention(spec.status)}
    ${renderSiteNavigation('requirements', '', Boolean(uiSpec), hasComponentComps)}
    <nav class="rd-section-nav" aria-label="Product requirement sections"><a href="#structure">Application</a><a href="#features">Capabilities</a><a href="#surfaces">Surfaces</a><a href="#use-cases">Workflows</a><a href="#requirements">Components</a><a href="#questions">Questions</a></nav>
    <main id="main-content" class="prd-main">
        <section id="structure" class="prd-section"><div class="prd-section-heading"><p class="rd-section-number">01</p><div><h2>Application organization</h2><p>${escapeHtml(spec.application.summary)}</p></div></div><article class="prd-shell"><div class="prd-article-heading"><div><p class="prd-kicker">${escapeHtml(spec.application.shell.kind)}</p><h3>Shell and navigation</h3></div></div><p>${escapeHtml(spec.application.shell.description)}</p>${attention(spec.application.shell.status)}<dl class="prd-facts"><div><dt>Intended users</dt><dd>${spec.product.users.map(escapeHtml).join(' ')}</dd></div>${shellNavigation}</dl>${shellStack}</article><h3 class="prd-subsection-heading">Activity areas</h3><div class="prd-card-grid">${spec.application.areas.map((area) => `<article class="prd-card" id="${anchor('area', area.id)}"><h3>${escapeHtml(area.name)}</h3><p>${escapeHtml(area.purpose)}</p>${attention(area.status)}${area.surfaceRefs.length ? `<p class="prd-links"><strong>Surfaces:</strong> ${area.surfaceRefs.map((ref) => `<a href="#${anchor('surface', ref)}">${escapeHtml(surfaces.get(ref).name)}</a>`).join(', ')}</p>` : '<p class="prd-muted">No surface has been designed for this area yet.</p>'}</article>`).join('')}</div>${supportingLinks}</section>
        <section id="features" class="prd-section"><div class="prd-section-heading"><p class="rd-section-number">02</p><div><h2>Product capabilities</h2><p>All peer capabilities are introduced before their detailed surfaces and workflows.</p></div></div><div class="prd-feature-list">${spec.features.map((feature) => `<article class="prd-feature" id="${anchor('feature', feature.id)}"><h3>${escapeHtml(feature.name)}</h3><p>${escapeHtml(feature.purpose)}</p>${attention(feature.status)}<dl class="prd-link-groups"><div><dt>Surfaces</dt><dd>${feature.surfaceRefs.map((ref) => `<a href="#${anchor('surface', ref)}">${escapeHtml(surfaces.get(ref).name)}</a>`).join(', ') || 'None yet'}</dd></div><div><dt>Workflows</dt><dd>${feature.useCaseRefs.map((ref) => `<a href="#${anchor('use-case', ref)}">${escapeHtml(useCases.get(ref).name)}</a>`).join(', ') || 'None yet'}</dd></div></dl></article>`).join('')}</div></section>
        <section id="surfaces" class="prd-section"><div class="prd-section-heading"><p class="rd-section-number">03</p><div><h2>Work surfaces</h2><p>Every surface is presented at the same depth before workflows or component detail.</p></div></div>${spec.surfaces.map((surface) => `<article class="prd-surface" id="${anchor('surface', surface.id)}"><div class="prd-article-heading"><div><p class="prd-kicker">${escapeHtml(surface.kind)}</p><h3>${escapeHtml(surface.name)}</h3></div><a href="#${anchor('area', surface.areaRef)}">${escapeHtml(areas.get(surface.areaRef).name)}</a></div><p>${escapeHtml(surface.purpose)}</p>${attention(surface.status)}<dl class="prd-facts"><div><dt>Entry</dt><dd>${escapeHtml(surface.entry)}</dd></div><div><dt>Exit</dt><dd>${escapeHtml(surface.exit)}</dd></div><div><dt>Focus intent</dt><dd>${escapeHtml(surface.focusIntent)}</dd></div></dl><ol class="prd-region-list">${[...surface.regions].sort((left, right) => left.order - right.order).map((region) => `<li><div><strong>${escapeHtml(region.name)}</strong><p>${escapeHtml(region.purpose)}</p><p class="prd-muted">${region.componentRefs.map((ref) => `<a href="#${anchor('component', ref)}">${escapeHtml(components.get(ref).name)}</a>`).join(' · ')}</p></div></li>`).join('')}</ol><p><strong>Relevant states:</strong> ${surface.states.map(escapeHtml).join(', ')}.</p>${renderSurfaceInteractionWireframes(spec, surface)}${scenesBySurface.get(surface.id).map(inlineComp).join('')}</article>`).join('')}</section>
        <section id="use-cases" class="prd-section"><div class="prd-section-heading"><p class="rd-section-number">04</p><div><h2>Workflows</h2><p>Each flow states its trigger, visible interactions, result, alternatives, and recovery.</p></div></div>${spec.useCases.map((useCase) => `<article class="prd-use-case" id="${anchor('use-case', useCase.id)}"><p class="prd-kicker"><a href="#${anchor('feature', useCase.featureRef)}">${escapeHtml(spec.features.find((feature) => feature.id === useCase.featureRef).name)}</a></p><h3>${escapeHtml(useCase.name)}</h3><p><strong>Goal:</strong> ${escapeHtml(useCase.goal)}</p>${attention(useCase.status)}<dl class="prd-facts"><div><dt>Trigger</dt><dd>${escapeHtml(useCase.trigger)}</dd></div><div><dt>Successful outcome</dt><dd>${escapeHtml(useCase.outcome)}</dd></div></dl><h4>Preconditions</h4>${renderList(useCase.preconditions)}<h4>Interactions</h4><ol class="prd-step-list">${useCase.steps.map((step) => `<li><p><strong>${escapeHtml(step.actor)}:</strong> ${escapeHtml(step.action)}</p><p class="prd-response"><strong>Visible response:</strong> ${escapeHtml(step.response)}</p></li>`).join('')}</ol>${useCase.alternatives.length ? `<h4>Alternatives and recovery</h4><div class="prd-alternatives">${useCase.alternatives.map((alternative) => `<article><h5>${escapeHtml(alternative.condition)}</h5><p>${escapeHtml(alternative.response)}</p><p><strong>Recovery:</strong> ${escapeHtml(alternative.recovery)}</p>${attention(alternative.status)}</article>`).join('')}</div>` : ''}</article>`).join('')}</section>
        <section id="requirements" class="prd-section"><div class="prd-section-heading"><p class="rd-section-number">05</p><div><h2>Component behavior</h2><p>These deeper requirements define capabilities, behavior, and states for UI design.</p></div></div><div class="prd-component-list">${spec.components.map((component) => `<article class="prd-requirement" id="${anchor('component', component.id)}"><p class="prd-kicker">${escapeHtml(component.kind)}</p><h3>${escapeHtml(component.name)}</h3><p>${escapeHtml(component.purpose)}</p>${attention(component.status)}<div class="prd-requirement-columns"><div><h4>Capabilities</h4>${renderList(component.capabilities)}</div><div><h4>Behavior</h4>${renderList(component.behaviorRequirements)}</div></div><p><strong>States:</strong> ${component.states.map(escapeHtml).join(', ')}.</p></article>`).join('')}</div></section>
        <section id="questions" class="prd-section"><div class="prd-section-heading"><p class="rd-section-number">06</p><div><h2>Open product and UX questions</h2><p>Only unresolved product behavior appears here; technical questions belong in engineering design review.</p></div></div>${openQuestions.length ? `<div class="prd-question-list">${openQuestions.map((question) => `<article id="${anchor('question', question.id)}"><h3>${escapeHtml(question.question)}</h3><p>${escapeHtml(question.why)}</p><p><strong>Decision owner:</strong> ${escapeHtml(question.owner)}</p><p class="prd-code">Affects: ${question.affects.map(escapeHtml).join(', ')}</p></article>`).join('')}</div>` : '<p>No open product or UX questions are recorded.</p>'}</section>
    </main>
    <footer><p>Generated from the structured UX specification. Update the product description and regenerate to change the design.</p></footer>
</body>
</html>\n`;
}

function iconSvg(document, iconId, label) {
    const icon = document.icons.find((candidate) => candidate.id === iconId);
    if (!icon) return '<span aria-hidden="true">?</span>';
    const geometry = iconGeometry(icon);
    if (!geometry) return '<span aria-hidden="true">?</span>';
    return `<svg viewBox="0 0 24 24" role="img" aria-label="${escapeHtml(label)}">${geometry.paths.map((item) => `<path d="${escapeHtml(item.d)}" opacity="${item.opacity}"></path>`).join('')}</svg>`;
}

function specimen(title, state, body, note = '') {
    return `<figure class="prd-state"><figcaption><strong>${escapeHtml(title)}</strong><span>${escapeHtml(state)}</span></figcaption><div class="prd-state-body">${body}</div>${note ? `<p>${escapeHtml(note)}</p>` : ''}</figure>`;
}

function renderButtonCatalog(document) {
    const button = document.button;
    const order = ['default', 'hover', 'pressed', 'focus', 'disabled', 'loading'];
    const stateSpecimens = order.filter((state) => button.states[state]).map((state) => specimen(button.label, state, `<button type="button" class="prd-button prd-button--contained prd-is-${state}"${state === 'disabled' ? ' disabled' : ''}>${state === 'loading' ? `<span class="prd-spinner" aria-hidden="true"></span>${escapeHtml(button.loadingLabel)}` : escapeHtml(button.label)}</button>`)).join('');
    const variants = [
        ['Contained', 'contained', button.label],
        ['Outlined', 'outlined', button.label],
        ['Text', 'text', button.label],
        ['Icon only', 'icon', iconSvg(document, document.buttonVariants.iconId, document.buttonVariants.accessibleLabel)],
    ];
    return `<section id="buttons" class="prd-catalog-section"><div class="prd-section-heading"><p class="rd-section-number">01</p><div><h2>Buttons</h2><p>Command states and the shared contained, outlined, text, and icon-only family.</p></div></div><div class="prd-state-grid">${stateSpecimens}</div><h3>Variants</h3><div class="prd-state-grid">${variants.map(([title, kind, content]) => specimen(title, 'default', `<button type="button" class="prd-button prd-button--${kind}"${kind === 'icon' ? ` aria-label="${escapeHtml(document.buttonVariants.accessibleLabel)}" title="${escapeHtml(document.buttonVariants.tooltip)}"` : ''}>${content}</button>`)).join('')}</div></section>`;
}

function fieldMarkup(field, state, index) {
    const inputId = `catalog-field-${state}-${index}`;
    const isError = state === 'error';
    return `<div class="prd-field prd-is-${state}"><label for="${inputId}">${escapeHtml(field.label)}</label><input id="${inputId}" value="${escapeHtml(field.value)}"${state === 'disabled' ? ' disabled' : ' readonly'}${isError ? ' aria-invalid="true" aria-describedby="catalog-field-error"' : ''}><p${isError ? ' id="catalog-field-error" class="prd-error"' : ''}>${escapeHtml(isError ? field.errorText : field.helperText)}</p></div>`;
}

function renderFieldCatalog(document) {
    const states = ['default', 'focused', 'disabled', 'error'];
    return `<section id="fields" class="prd-catalog-section"><div class="prd-section-heading"><p class="rd-section-number">02</p><div><h2>Text fields and feedback</h2><p>Outlined fields retain one helper or corrective message region below the input.</p></div></div><div class="prd-state-grid">${states.map((state, index) => specimen(document.textField.label, state, fieldMarkup(document.textField, state, index))).join('')}</div><article class="prd-pattern"><h3>Shared field feedback</h3><div class="prd-feedback-pair"><p>${escapeHtml(document.textField.helperText)}</p><p class="prd-error">${escapeHtml(document.textField.errorText)}</p></div></article></section>`;
}

function renderChoiceCatalog(document) {
    const group = document.compositeInput;
    const selected = new Set(group.selectedIds);
    const groupMarkup = (state) => `<fieldset class="prd-choice-group prd-is-${state}"${state === 'disabled' ? ' disabled' : ''}><legend>${escapeHtml(group.label)}</legend>${group.options.map((option) => `<label><input type="checkbox"${selected.has(option.id) ? ' checked' : ''}><span>${escapeHtml(option.label)}</span></label>`).join('')}<p class="${state === 'error' ? 'prd-error' : ''}">${escapeHtml(state === 'error' ? group.errorText : group.helperText)}</p></fieldset>`;
    return `<section id="choices" class="prd-catalog-section"><div class="prd-section-heading"><p class="rd-section-number">03</p><div><h2>Checkbox groups</h2><p>A composite choice owns one visible label and one feedback region.</p></div></div><div class="prd-state-grid">${['default', 'selected', 'disabled', 'error'].map((state) => specimen(group.label, state, groupMarkup(state))).join('')}</div></section>`;
}

function renderSelectCatalog(document) {
    const select = document.selectInput;
    const selected = select.options.find((option) => option.id === select.selectedId);
    const closed = (state, index) => `<div class="prd-field prd-select prd-is-${state}"><label for="catalog-select-${index}">${escapeHtml(select.label)}</label><select id="catalog-select-${index}"${state === 'disabled' ? ' disabled' : ''}${state === 'error' ? ' aria-invalid="true"' : ''}>${select.options.map((option) => `<option${option.id === select.selectedId ? ' selected' : ''}${option.disabled ? ' disabled' : ''}>${escapeHtml(option.label)}</option>`).join('')}</select><p class="${state === 'error' ? 'prd-error' : ''}">${escapeHtml(state === 'error' ? select.errorText : select.helperText)}</p></div>`;
    const open = `<div class="prd-select-open"><span class="prd-floating-label">${escapeHtml(select.label)}</span><button type="button" aria-haspopup="listbox" aria-expanded="true">${escapeHtml(selected.label)}<span aria-hidden="true">▴</span></button><ul role="listbox" aria-label="${escapeHtml(select.label)}">${select.options.map((option) => `<li role="option" aria-selected="${option.id === select.selectedId}"${option.disabled ? ' aria-disabled="true"' : ''} class="${option.id === select.activeId ? 'prd-is-active' : ''}">${escapeHtml(option.label)}${option.id === select.selectedId ? '<span aria-hidden="true">✓</span>' : ''}</li>`).join('')}</ul><p>${escapeHtml(select.helperText)}</p></div>`;
    return `<section id="selects" class="prd-catalog-section"><div class="prd-section-heading"><p class="rd-section-number">04</p><div><h2>Selects</h2><p>Selected and keyboard-active options remain distinct, and unavailable options stay identifiable.</p></div></div><div class="prd-state-grid">${specimen(select.label, 'closed', closed('default', 0))}${specimen(select.label, 'focused', closed('focused', 1))}${specimen(select.label, 'open', open)}${specimen(select.label, 'disabled', closed('disabled', 2))}${specimen(select.label, 'error', closed('error', 3))}</div></section>`;
}

function renderEmbeddedFieldCatalog(document) {
    const password = document.password;
    const inputId = 'catalog-password';
    return `<section id="embedded-fields" class="prd-catalog-section"><div class="prd-section-heading"><p class="rd-section-number">05</p><div><h2>Embedded-action fields</h2><p>The password specimen demonstrates a recognizable field with an internal icon button; it does not add a password feature to the product.</p></div></div><div class="prd-state-grid">${specimen(password.label, 'masked', `<div class="prd-embedded-field"><label for="${inputId}">${escapeHtml(password.label)}</label><input id="${inputId}" value="${'•'.repeat(password.maskedLength)}" readonly><button type="button" aria-label="Show value" title="Show value">${iconSvg(document, password.icons.visible, 'Show value')}</button><p>${escapeHtml(password.helperText)}</p></div><ul class="prd-rule-list">${password.rules.map((rule) => `<li class="${rule.passed ? 'prd-rule-pass' : 'prd-rule-fail'}">${iconSvg(document, rule.passed ? password.icons.pass : password.icons.fail, rule.passed ? 'Requirement met' : 'Requirement not met')}<span>${escapeHtml(rule.text)}</span></li>`).join('')}</ul>`)}</div></section>`;
}

function renderComponentCatalog(document, hasComps = false, hasComponentComps = false) {
    return `<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="generator" content="${GENERATOR}">
    <title>${escapeHtml(document.theme.name)} Component States</title>
    <link rel="stylesheet" href="../assets/prd.css">
    <link rel="stylesheet" href="../assets/product.css">
</head>
<body>
    <!-- ${TEXT_MARKER} -->
    <a class="rd-skip-link" href="#main-content">Skip to content</a>
    <header class="rd-page-header"><div><p class="rd-eyebrow">Component reference</p><h1>Standard component states</h1><p class="rd-lede">Reusable visual and accessibility treatments for ordinary application components. Product-specific interactions receive separate comps.</p></div><dl class="rd-source-summary"><div><dt>Revision</dt><dd>${document.revision}</dd></div><div><dt>Components</dt><dd>7</dd></div><div><dt>Theme</dt><dd>${escapeHtml(document.theme.name)}</dd></div></dl></header>
    ${renderSiteNavigation('components', '../', hasComps, hasComponentComps)}
    <nav class="rd-section-nav" aria-label="Component sections"><a href="#buttons">Buttons</a><a href="#fields">Fields</a><a href="#choices">Choices</a><a href="#selects">Selects</a><a href="#embedded-fields">Embedded fields</a></nav>
    <main id="main-content" class="prd-main prd-catalog">${renderButtonCatalog(document)}${renderFieldCatalog(document)}${renderChoiceCatalog(document)}${renderSelectCatalog(document)}${renderEmbeddedFieldCatalog(document)}</main>
    <footer><p>Generated from structured design-language component records. Change the source and regenerate rather than editing this page.</p></footer>
</body>
</html>\n`;
}

function renderProductCss() {
    return `/* ${TEXT_MARKER} */
.prd-main { width: min(100%, var(--rd-page-max)); margin: 0 auto; padding: 0 var(--rd-page-gutter) var(--rd-space-12); }
.prd-section, .prd-catalog-section { padding: var(--rd-space-12) 0; border-bottom: 1px solid var(--rd-review-rule); }
.prd-section-heading { display: grid; grid-template-columns: 48px minmax(0, 1fr); gap: var(--rd-space-4); margin-bottom: var(--rd-space-6); }
.prd-section-heading .rd-section-number { margin-top: 5px; }
.prd-card-grid, .prd-state-grid, .prd-question-list { display: grid; grid-template-columns: repeat(auto-fit, minmax(min(100%, 280px), 1fr)); gap: var(--rd-space-4); }
.prd-card, .prd-feature, .prd-surface, .prd-use-case, .prd-requirement, .prd-question-list article, .prd-state, .prd-pattern { padding: var(--rd-space-6); border: 1px solid var(--rd-color-panel-border); border-radius: var(--rd-radius-card); background: var(--rd-review-card); }
.prd-shell { margin-bottom: var(--rd-space-8); padding: var(--rd-space-6); border: 1px solid var(--rd-color-panel-border); border-radius: var(--rd-radius-card); background: var(--rd-review-card); }
.prd-shell-stack { display: grid; gap: var(--rd-space-2); margin: var(--rd-space-5) 0 0; padding: 0; list-style: none; }
.prd-shell-stack li { position: relative; padding: var(--rd-space-4); border: 1px solid var(--rd-color-panel-border); border-radius: var(--rd-radius-small); background: var(--rd-review-soft-alt); }
.prd-shell-stack li + li::before { position: absolute; top: calc(-1 * var(--rd-space-2) - 1px); left: 50%; width: 1px; height: var(--rd-space-2); background: var(--rd-color-panel-border); content: ''; }
.prd-shell-stack h4, .prd-shell-stack p { margin: 0; }
.prd-subsection-heading { margin: 0 0 var(--rd-space-4); }
.prd-supporting-links { display: flex; flex-wrap: wrap; gap: var(--rd-space-3); margin-top: var(--rd-space-6); padding-top: var(--rd-space-4); border-top: 1px solid var(--rd-review-rule); }
.prd-supporting-links strong { margin-right: auto; }
.prd-feature-list, .prd-component-list { display: grid; gap: var(--rd-space-4); }
.prd-feature { display: grid; grid-template-columns: minmax(0, 1fr) minmax(240px, 0.45fr); gap: 0 var(--rd-space-6); }
.prd-feature > h3, .prd-feature > p, .prd-feature > .prd-attention { grid-column: 1; }
.prd-link-groups { grid-column: 2; grid-row: 1 / span 4; margin: 0; }
.prd-link-groups div + div { margin-top: var(--rd-space-3); }
.prd-link-groups dt, .prd-facts dt { color: var(--rd-review-label); font-size: 12px; font-weight: 700; text-transform: uppercase; }
.prd-link-groups dd, .prd-facts dd { margin: 2px 0 0; }
.prd-surface, .prd-use-case { margin-bottom: var(--rd-space-6); }
.prd-article-heading { display: flex; justify-content: space-between; gap: var(--rd-space-4); align-items: start; }
.prd-kicker { margin-bottom: var(--rd-space-1); color: var(--rd-review-label); font-size: 12px; font-weight: 700; letter-spacing: .08em; text-transform: uppercase; }
.prd-facts { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: var(--rd-space-4); margin: var(--rd-space-6) 0; padding: var(--rd-space-4); background: var(--rd-review-soft-alt); }
.prd-region-list, .prd-step-list { display: grid; gap: var(--rd-space-3); padding-left: 28px; }
.prd-region-list li::marker, .prd-step-list li::marker { color: var(--rd-color-primary-action); font-weight: 700; }
.prd-region-list p, .prd-step-list p { margin-bottom: var(--rd-space-1); }
.prd-response { color: var(--rd-review-muted-strong); }
.prd-alternatives { display: grid; grid-template-columns: repeat(auto-fit, minmax(min(100%, 260px), 1fr)); gap: var(--rd-space-3); }
.prd-alternatives article { padding: var(--rd-space-4); border-left: 3px solid var(--rd-color-panel-border); background: var(--rd-review-soft-alt); }
.prd-alternatives h5 { margin: 0 0 var(--rd-space-2); font-size: 14px; }
.prd-attention { padding: var(--rd-space-2) var(--rd-space-3); border-left: 3px solid var(--rd-color-warning); background: var(--rd-review-warning-bg); color: var(--rd-review-warning-text); }
.prd-muted { color: var(--rd-review-muted); }
.prd-comp-links { display: grid; gap: var(--rd-space-2); margin-top: var(--rd-space-4); padding-top: var(--rd-space-4); border-top: 1px solid var(--rd-color-panel-border); }
.prd-comp-links > div, .prd-comp-actions { display: flex; flex-wrap: wrap; align-items: center; gap: var(--rd-space-2); }
.prd-comp-links > div span { margin-right: auto; }
.prd-comp-links a, .prd-comp-actions a { padding: 6px 10px; border-radius: var(--rd-radius-small); background: var(--rd-color-primary-action); color: var(--rd-color-on-primary); text-decoration: none; }
.prd-comp-inline { margin: var(--rd-space-8) 0 0; padding: var(--rd-space-4); border: 1px solid var(--rd-color-panel-border); border-radius: var(--rd-radius-card); background: var(--rd-review-soft); }
.prd-comp-inline-heading { display: flex; flex-wrap: wrap; align-items: end; justify-content: space-between; gap: var(--rd-space-4); margin-bottom: var(--rd-space-3); }
.prd-comp-inline-heading h4, .prd-comp-inline-heading p { margin: 0; }
.prd-comp-inline .prd-comp-canvas { display: block; width: 100%; height: var(--ui-viewport-height); min-width: 0; border: 1px solid var(--rd-color-panel-border); border-radius: var(--rd-radius-small); background: var(--rd-color-surface); }
.prd-comp-inline .ui-complex-component { overflow: hidden; }
.prd-comp-inline figcaption { margin-top: var(--rd-space-2); color: var(--rd-review-muted); font-size: 12px; line-height: 16px; }
.prd-code { font-family: ui-monospace, SFMono-Regular, Consolas, monospace; font-size: 12px; }
.prd-requirement-columns { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: var(--rd-space-6); }
.prd-state { min-width: 0; margin: 0; }
.prd-state figcaption { display: flex; justify-content: space-between; gap: var(--rd-space-3); margin-bottom: var(--rd-space-4); }
.prd-state figcaption span { color: var(--rd-review-label); font-size: 12px; text-transform: capitalize; }
.prd-state-body { display: grid; align-content: center; min-height: 140px; padding: var(--rd-space-4); border-radius: var(--rd-radius-small); background: var(--rd-review-soft-alt); }
.prd-button { display: inline-flex; align-items: center; justify-content: center; gap: var(--rd-space-2); width: max-content; min-width: 128px; min-height: var(--rd-control-button-height); padding: 0 var(--rd-control-button-padding-x); border: 1px solid transparent; border-radius: var(--rd-control-button-radius); font: inherit; font-weight: 500; cursor: default; }
.prd-button--contained { background: var(--rd-color-primary-action); color: var(--rd-color-on-primary); }
.prd-button--outlined { border-color: color-mix(in srgb, var(--rd-color-primary-action) 50%, var(--rd-color-surface)); background: var(--rd-color-surface); color: var(--rd-color-primary-action); }
.prd-button--text, .prd-button--icon { background: transparent; color: var(--rd-color-primary-action); }
.prd-button--icon { min-width: var(--rd-control-button-height); padding: 0; }
.prd-button--icon svg, .prd-embedded-field button svg, .prd-rule-list svg { width: 20px; height: 20px; fill: currentColor; }
.prd-button.prd-is-hover { background: color-mix(in srgb, var(--rd-color-primary-action) 70%, var(--rd-color-state-overlay)); }
.prd-button.prd-is-pressed { background: color-mix(in srgb, var(--rd-color-primary-action) 60%, var(--rd-color-state-overlay)); }
.prd-button.prd-is-focus { outline: 2px solid var(--rd-color-primary-action); outline-offset: 2px; }
.prd-button:disabled { background: var(--rd-color-disabled-background); color: var(--rd-review-muted); }
.prd-spinner { width: 16px; height: 16px; border: 2px solid currentColor; border-right-color: transparent; border-radius: 50%; }
.prd-field, .prd-embedded-field { position: relative; display: grid; gap: var(--rd-layout-helper-gap); }
.prd-field label, .prd-embedded-field label, .prd-floating-label { position: absolute; z-index: 1; top: 0; left: 10px; padding: 0 4px; background: var(--rd-color-surface); color: var(--rd-review-label); font-size: var(--rd-type-field-label-size); line-height: var(--rd-type-field-label-line); transform: translateY(-50%); }
.prd-field input, .prd-field select, .prd-embedded-field input, .prd-select-open > button { width: 100%; min-height: var(--rd-control-field-height); padding: 0 var(--rd-control-field-padding-x); border: 1px solid var(--rd-color-panel-border); border-radius: var(--rd-control-field-radius); background: var(--rd-color-surface); color: var(--rd-color-body-text); font: inherit; }
.prd-field p, .prd-embedded-field p, .prd-select-open p { margin: 0; padding-left: var(--rd-control-field-padding-x); color: var(--rd-review-muted); font-size: var(--rd-type-field-message-size); line-height: var(--rd-type-field-message-line); }
.prd-field.prd-is-focused input, .prd-field.prd-is-focused select, .prd-field.prd-is-error input, .prd-field.prd-is-error select { border-width: 2px; }
.prd-field.prd-is-focused input, .prd-field.prd-is-focused select { border-color: var(--rd-color-primary-action); }
.prd-field.prd-is-error input, .prd-field.prd-is-error select { border-color: var(--rd-color-failure); }
.prd-error { color: var(--rd-color-failure) !important; }
.prd-feedback-pair { display: grid; gap: var(--rd-space-2); }
.prd-choice-group { display: grid; gap: var(--rd-space-2); margin: 0; padding: var(--rd-space-3); border: 1px solid var(--rd-color-panel-border); border-radius: var(--rd-control-field-radius); }
.prd-choice-group label { display: flex; gap: var(--rd-space-2); align-items: center; }
.prd-choice-group p { margin: var(--rd-space-1) 0 0; font-size: var(--rd-type-field-message-size); }
.prd-select-open { position: relative; display: grid; gap: var(--rd-space-1); }
.prd-select-open > button { display: flex; justify-content: space-between; align-items: center; }
.prd-select-open ul { display: grid; gap: 2px; margin: 0; padding: var(--rd-space-2); border: 1px solid var(--rd-color-panel-border); border-radius: var(--rd-radius-small); background: var(--rd-color-surface); list-style: none; }
.prd-select-open li { display: flex; justify-content: space-between; min-height: 36px; padding: 6px var(--rd-space-3); }
.prd-select-open li[aria-selected='true'] { background: color-mix(in srgb, var(--rd-color-primary-action) 8%, var(--rd-color-surface)); }
.prd-select-open li.prd-is-active { outline: 2px solid var(--rd-color-primary-action); outline-offset: -2px; }
.prd-select-open li[aria-disabled='true'] { color: var(--rd-review-muted); }
.prd-embedded-field { grid-template-columns: minmax(0, 1fr) 40px; }
.prd-embedded-field label, .prd-embedded-field p { grid-column: 1 / -1; }
.prd-embedded-field input { grid-column: 1 / -1; grid-row: 1; padding-right: 52px; }
.prd-embedded-field button { z-index: 1; grid-column: 2; grid-row: 1; border: 0; background: transparent; color: var(--rd-color-primary-action); }
.prd-rule-list { display: grid; gap: var(--rd-space-2); margin: var(--rd-space-4) 0 0; padding: 0; list-style: none; }
.prd-rule-list li { display: flex; gap: var(--rd-space-2); align-items: center; }
.prd-rule-pass { color: var(--rd-color-success); }
.prd-rule-fail { color: var(--rd-color-failure); }
@media (max-width: 760px) { .prd-section-heading { grid-template-columns: 1fr; } .prd-feature { grid-template-columns: 1fr; } .prd-link-groups { grid-column: 1; grid-row: auto; } .prd-requirement-columns { grid-template-columns: 1fr; } }
${renderUxInteractionWireframeCss()}
`;
}

function assertSafeOutputPath(outputRoot, relativePath) {
    const root = path.resolve(outputRoot);
    const target = path.resolve(root, relativePath);
    if (target !== root && !target.startsWith(`${root}${path.sep}`)) fail(`Output escapes destination: ${relativePath}`);
    if (fs.existsSync(root) && fs.lstatSync(root).isSymbolicLink()) fail(`Refusing linked output root: ${root}`);
    let current = root;
    for (const part of path.relative(root, target).split(path.sep).slice(0, -1)) {
        current = path.join(current, part);
        if (fs.existsSync(current) && fs.lstatSync(current).isSymbolicLink()) fail(`Refusing linked output path: ${current}`);
    }
    if (fs.existsSync(target) && fs.lstatSync(target).isSymbolicLink()) fail(`Refusing linked output file: ${target}`);
    return target;
}

function assertOwnedOutput(target, relativePath, content) {
    if (!fs.existsSync(target)) return;
    if (Buffer.isBuffer(content)) {
        if (!fs.readFileSync(target).equals(content)) fail(`Refusing to overwrite an unowned or changed media asset: ${relativePath}`);
        return;
    }
    const existing = fs.readFileSync(target, 'utf8');
    if (relativePath.endsWith('render-report.json')) {
        let report;
        try { report = JSON.parse(existing); } catch { fail('Refusing to overwrite an unowned render report'); }
        if (![GENERATOR, DESIGN_GENERATOR, UI_COMPOSITION_HTML_GENERATOR, COMPONENT_DESIGN_HTML_GENERATOR].includes(report.generator)) fail('Refusing to overwrite an unowned render report');
        return;
    }
    if (![TEXT_MARKER, UI_COMPOSITION_HTML_MARKER].some(marker => existing.includes(marker))) fail(`Refusing to overwrite an unowned generated file: ${relativePath}`);
}

function planOutputs(outputRoot, outputs) {
    return [...outputs].map(([relativePath, content]) => {
        const target = assertSafeOutputPath(outputRoot, relativePath);
        assertOwnedOutput(target, relativePath, content);
        return {target, content};
    });
}

function publishOutputs(planned) {
    for (const {target} of planned) fs.mkdirSync(path.dirname(target), {recursive: true});
    for (const {target, content} of planned) fs.writeFileSync(target, content, Buffer.isBuffer(content) ? undefined : 'utf8');
}

function countStatuses(value, status) {
    if (Array.isArray(value)) return value.reduce((total, item) => total + countStatuses(item, status), 0);
    if (!value || typeof value !== 'object') return 0;
    return (value.status === status ? 1 : 0) + Object.values(value).reduce((total, item) => total + countStatuses(item, status), 0);
}

function renderComponentCompIndex(componentInputs) {
    const cards = componentInputs.map(({value}) => {
        const links = value.renderRequests.map(request => {
            const label = request.variant === 'annotated' ? 'Annotated view' : 'Clean view';
            return `<a href="${escapeHtml(request.output.replace(/^comps\//, ''))}">${label}</a>`;
        }).join('');
        const states = value.componentTemplate.supportedStates.map(state => `<li>${escapeHtml(state)}</li>`).join('');
        return `<article><p class="rd-eyebrow">${escapeHtml(value.artifactKind)}</p><h2>${escapeHtml(value.componentTemplate.name)}</h2><p>${escapeHtml(value.componentTemplate.uxRef)}</p><ul>${states}</ul><div class="rd-actions">${links}</div></article>`;
    }).join('');
    return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="generator" content="${COMPONENT_DESIGN_HTML_GENERATOR}"><title>Component comps</title><link rel="stylesheet" href="../assets/prd.css"><link rel="stylesheet" href="../assets/product.css"></head><body><!-- ${UI_COMPOSITION_HTML_MARKER} --><nav class="prd-site-nav" aria-label="Product design"><a href="../index.html">Product requirements</a><a href="../design-language/index.html">Design language</a><a href="../components/index.html">Component states</a><span aria-current="page">Component comps</span><a href="../comps/index.html">Product comps</a></nav><header class="prd-hero"><p class="rd-eyebrow">Focused component design</p><h1>Component comps</h1><p>Clean and annotated views generated from independently owned component specifications.</p></header><main class="prd-card-grid">${cards}</main></body></html>`;
}

/** Publish the static PRD index, component catalog, design-language section, shared assets, and aggregate report. */
export function publishPrdHtml(uxSourceFile, designSourceFile, outputRoot, options = {}) {
    const uxInput = readJson(uxSourceFile, 'UX source');
    const designInput = readJson(designSourceFile, 'Design-language source');
    validateUxSpec(uxInput.value);
    validateDesignLanguage(designInput.value, true);
    if (designInput.value.schemaVersion !== '0.14') fail('The static PRD publisher requires saved design-language schema 0.14 data');

    const uiInput = options.uiFile ? readJson(options.uiFile, 'UI composition source') : null;
    const componentFiles = options.componentFiles ?? (options.componentFile ? [options.componentFile] : []);
    const componentLabels = options.componentLabels ?? (options.componentLabel ? [options.componentLabel] : []);
    const componentInputs = componentFiles.map((file, index) => ({
        ...readJson(file, `Component-design source ${index + 1}`),
        label: componentLabels[index],
    }));
    if (componentInputs.length && !uiInput) fail('Component-design publication requires --ui so placeholder replacements can be validated');
    if ((uiInput || componentInputs.length) && !options.sourceRoot) fail('UI and component publication requires an explicit sourceRoot');
    const sourceRoot = options.sourceRoot ? path.resolve(options.sourceRoot) : undefined;
    const uiAssetRoot = uiInput ? authorizeAssetRoot(options.uiAssetRoot ?? path.dirname(uiInput.absolute), sourceRoot, 'UI assetRoot').assetRoot : undefined;
    const requestedComponentAssetRoots = options.componentAssetRoots ?? [];
    if (requestedComponentAssetRoots.length && requestedComponentAssetRoots.length !== componentInputs.length) fail('Each component requires exactly one --component-asset-root when explicit component asset roots are supplied');
    const componentAssetRoots = componentInputs.map((componentInput, index) => authorizeAssetRoot(
        requestedComponentAssetRoots[index] ?? path.dirname(componentInput.absolute),
        sourceRoot,
        `component ${index + 1} assetRoot`,
    ).assetRoot);
    const componentBuilds = componentInputs.map((componentInput, index) => buildComponentDesignHtml(componentInput.value, {
        uxSpec: uxInput.value,
        designLanguage: designInput.value,
        componentSource: componentInput.source,
        uxSource: uxInput.source,
        designSource: designInput.source,
        componentLabel: componentInput.label ?? path.basename(componentInput.absolute),
        uxLabel: options.uxLabel ?? path.basename(uxInput.absolute),
        designLabel: options.designLabel ?? path.basename(designInput.absolute),
        assetRoot: componentAssetRoots[index],
        sourceRoot,
    }));
    const componentRegistrations = componentInputs.map((componentInput, index) => buildComponentRegistration(componentInput.value, uiInput.value, {
        uxSpec: uxInput.value,
        designLanguage: designInput.value,
        sourceRoot,
        componentAssetRoot: componentAssetRoots[index],
        surfaceAssetRoot: uiAssetRoot,
    }));
    const inlineComponentRegistrations = componentRegistrations.map((registration, index) => ({...registration, inlineSpec: componentInputs[index].value}));
    const uiBuild = uiInput ? buildUiCompositionHtml(uiInput.value, {
        uxSpec: uxInput.value,
        designLanguage: designInput.value,
        uiSource: uiInput.source,
        uxSource: uxInput.source,
        designSource: designInput.source,
        uiLabel: options.uiLabel ?? path.basename(uiInput.absolute),
        uxLabel: options.uxLabel ?? path.basename(uxInput.absolute),
        designLabel: options.designLabel ?? path.basename(designInput.absolute),
        componentRegistrations: inlineComponentRegistrations,
        assetRoot: uiAssetRoot,
        sourceRoot,
    }) : null;

    const hasComponents = componentInputs.length > 0;
    const index = renderPrdIndex(uxInput.value, uiInput?.value ?? null, hasComponents, inlineComponentRegistrations);
    const components = renderComponentCatalog(designInput.value, Boolean(uiInput), hasComponents);
    const css = renderProductCss();
    const openQuestions = uxInput.value.openQuestions.filter((question) => question.status === 'open').length;
    const unresolvedRecords = countStatuses(uxInput.value, 'unresolved');
    const lockedRecords = countStatuses(uxInput.value, 'locked') + (designInput.value.status === 'locked' ? 1 : 0) + (uiInput ? countStatuses(uiInput.value, 'locked') : 0) + componentInputs.reduce((total, input) => total + countStatuses(input.value, 'locked'), 0);
    const files = ['index.html', 'components/index.html', 'assets/product.css', 'render-report.json'];
    const report = {
        generator: GENERATOR,
        rendererVersion: VERSION,
        sources: {
            ux: {id: uxInput.value.id, schemaVersion: uxInput.value.schemaVersion, revision: uxInput.value.revision, sha256: sourceHash(uxInput.source), label: options.uxLabel ?? path.basename(uxInput.absolute)},
            designLanguage: {id: designInput.value.id, schemaVersion: designInput.value.schemaVersion, revision: designInput.value.revision, sha256: sourceHash(designInput.source), label: options.designLabel ?? path.basename(designInput.absolute)},
            ...(uiInput ? {ui: {id: uiInput.value.id, schemaVersion: uiInput.value.schemaVersion, revision: uiInput.value.revision, sha256: sourceHash(uiInput.source), label: options.uiLabel ?? path.basename(uiInput.absolute)}} : {}),
            ...(componentInputs.length === 1 ? {component: {id: componentInputs[0].value.id, schemaVersion: componentInputs[0].value.schemaVersion, revision: componentInputs[0].value.revision, sha256: sourceHash(componentInputs[0].source), label: componentInputs[0].label ?? path.basename(componentInputs[0].absolute)}} : {}),
            ...(hasComponents ? {components: componentInputs.map(componentInput => ({id: componentInput.value.id, schemaVersion: componentInput.value.schemaVersion, revision: componentInput.value.revision, sha256: sourceHash(componentInput.source), label: componentInput.label ?? path.basename(componentInput.absolute)}))} : {}),
        },
        designLanguageReport: 'design-language/render-report.json',
        ...(uiInput ? {uiCompositionReport: 'ui/render-report.json'} : {}),
        ...(componentInputs.length === 1 ? {componentDesignReport: `ui/components/${componentInputs[0].value.componentTemplate.id}-render-report.json`} : {}),
        ...(hasComponents ? {componentDesignReports: componentInputs.map(componentInput => `ui/components/${componentInput.value.componentTemplate.id}-render-report.json`)} : {}),
        outcome: openQuestions || unresolvedRecords || designInput.value.unspecifiedRequirements.length ? 'partial' : 'complete',
        counts: {
            applicationAreas: uxInput.value.application.areas.length,
            features: uxInput.value.features.length,
            surfaces: uxInput.value.surfaces.length,
            useCases: uxInput.value.useCases.length,
            uxActions: uxInput.value.actions.length,
            uxInteractionFrames: uxInput.value.interactionFrames.length,
            wireframedSurfaces: uxInput.value.surfaces.filter(surface => surface.interactionFrameRefs.length).length,
            productComponents: uxInput.value.components.length,
            standardComponents: 7,
            openQuestions,
            unresolvedRecords,
            lockedRecords,
            ...(uiInput ? {uiScenes: uiInput.value.scenes.length, uiRenderRequests: uiInput.value.renderRequests.length, uiPlaceholders: uiBuild.report.counts.placeholders} : {}),
            ...(hasComponents ? {componentDesigns: componentInputs.length, componentScenes: componentInputs.reduce((total, componentInput) => total + componentInput.value.scenes.length, 0), componentRenderRequests: componentInputs.reduce((total, componentInput) => total + componentInput.value.renderRequests.length, 0), resolvedUiPlaceholders: uiBuild.report.counts.resolvedPlaceholders, unresolvedUiPlaceholders: uiBuild.report.counts.unresolvedPlaceholders} : {}),
        },
        files: [...new Set([...files, 'design-language/index.html', 'design-language/render-report.json', 'assets/prd.css', ...(uiBuild ? uiBuild.report.files : []), ...componentBuilds.flatMap(componentBuild => componentBuild.report.files)])].sort(),
    };
    const outputs = new Map([
        ['index.html', index],
        ['components/index.html', components],
        ['assets/product.css', css],
        ['render-report.json', `${JSON.stringify(report, null, 2)}\n`],
        ...(uiBuild ? [...uiBuild.outputs] : []),
        ...componentBuilds.flatMap(componentBuild => [...componentBuild.outputs]),
        ...(hasComponents ? [['component-comps/index.html', renderComponentCompIndex(componentInputs)]] : []),
    ]);
    const planned = planOutputs(outputRoot, outputs);

    const designReport = publishDesignLanguageHtml(designInput.absolute, outputRoot, {
        title: options.designTitle,
        sourceLabel: options.designLabel,
        layoutFile: options.layoutFile,
        layoutLabel: options.layoutLabel,
        siteNavigation: true,
        reportPath: 'design-language/render-report.json',
    });
    for (const dependency of ['design-language/index.html', 'design-language/render-report.json', 'assets/prd.css']) {
        const file = assertSafeOutputPath(outputRoot, dependency);
        if (!fs.statSync(file, {throwIfNoEntry: false})?.isFile()) fail(`Required generated dependency is missing: ${dependency}`);
    }
    publishOutputs(planned);
    return {...report, designLanguage: designReport, ...(uiBuild ? {uiComposition: uiBuild.report} : {}), ...(componentBuilds.length === 1 ? {componentDesign: componentBuilds[0].report} : {}), ...(hasComponents ? {componentDesigns: componentBuilds.map(componentBuild => componentBuild.report)} : {}), outputRoot: path.resolve(outputRoot)};
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
    try {
        const [uxSource, designSource, outputRoot, ...args] = process.argv.slice(2);
        if (!uxSource || !designSource || !outputRoot) fail('Usage: node prd-html.mjs <ux-spec.json> <design-language.json> <output-root> [--source-root <authoritative-source-root>] [--ui <ui-spec.json>] [--ui-asset-root <asset-root>] [--component <component-design.json>]... [--component-asset-root <asset-root>]... [--layout <review-layout.json>] [--ux-label <label>] [--design-label <label>] [--ui-label <label>] [--component-label <label>]... [--layout-label <label>] [--design-title <title>]');
        const options = {};
        for (let index = 0; index < args.length; index += 2) {
            const flag = args[index];
            const value = args[index + 1];
            if (!value) fail(`Missing value for ${flag}`);
            if (flag === '--layout') options.layoutFile = value;
            else if (flag === '--source-root') options.sourceRoot = path.resolve(value);
            else if (flag === '--ui') options.uiFile = value;
            else if (flag === '--ui-asset-root') options.uiAssetRoot = path.resolve(value);
            else if (flag === '--component') (options.componentFiles ??= []).push(value);
            else if (flag === '--component-asset-root') (options.componentAssetRoots ??= []).push(path.resolve(value));
            else if (flag === '--ux-label') options.uxLabel = value;
            else if (flag === '--design-label') options.designLabel = value;
            else if (flag === '--ui-label') options.uiLabel = value;
            else if (flag === '--component-label') (options.componentLabels ??= []).push(value);
            else if (flag === '--layout-label') options.layoutLabel = value;
            else if (flag === '--design-title') options.designTitle = value;
            else fail(`Unknown option: ${flag}`);
        }
        process.stdout.write(`${JSON.stringify(publishPrdHtml(uxSource, designSource, outputRoot, options), null, 2)}\n`);
    } catch (error) {
        process.stderr.write(`${error.message}\n`);
        process.exitCode = 1;
    }
}
